"""add chat room and message

Revision ID: 10d58048ab7f
Revises: b2ce8bce83e6
Create Date: 2026-07-08 06:39:37.031438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10d58048ab7f'
down_revision: Union[str, None] = 'b2ce8bce83e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_room',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('sighting_id', sa.BigInteger(), nullable=False),
    sa.Column('owner_user_id', sa.BigInteger(), nullable=False),
    sa.Column('participant_user_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_message_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['participant_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sighting_id'], ['sighting.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sighting_id', 'owner_user_id', 'participant_user_id', name='uq_chat_room')
    )
    op.create_table('chat_message',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.BigInteger(), nullable=False),
    sa.Column('sender_user_id', sa.BigInteger(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['chat_room.id'], ),
    sa.ForeignKeyConstraint(['sender_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_message')
    op.drop_table('chat_room')
    # ### end Alembic commands ###
