"""add is_deleted to sighting

Revision ID: 37410d06cfc9
Revises: c13ac725aea0
Create Date: 2026-06-19 05:20:56.494499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37410d06cfc9'
down_revision: Union[str, None] = 'c13ac725aea0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'sighting',
        sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.text('0'))
    )
    op.alter_column(
        'sighting',
        'is_deleted',
        server_default=None,
        existing_type=sa.Boolean(),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sighting', 'is_deleted')
    # ### end Alembic commands ###
