"""add user_id to sighting

Revision ID: b81127cb6c13
Revises: b701f74545db
Create Date: 2026-05-28 07:47:10.492287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b81127cb6c13'
down_revision: Union[str, None] = 'b701f74545db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sighting', sa.Column('user_id', sa.BigInteger(), nullable=False))
    op.create_foreign_key(None, 'sighting', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sighting', type_='foreignkey')
    op.drop_column('sighting', 'user_id')
    # ### end Alembic commands ###
