"""add post_type to sighting

Revision ID: c13ac725aea0
Revises: b81127cb6c13
Create Date: 2026-06-18 05:09:42.076238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c13ac725aea0'
down_revision: Union[str, None] = 'b81127cb6c13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sighting', sa.Column('post_type', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sighting', 'post_type')
    # ### end Alembic commands ###
