"""add resolved_at and reopen fields to sighting

Revision ID: de8a74df38ac
Revises: 81b22a268b87
Create Date: 2026-06-24 01:42:41.528717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de8a74df38ac'
down_revision: Union[str, None] = '81b22a268b87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sighting', sa.Column('resolved_at', sa.DateTime(), nullable=True))
    op.add_column('sighting', sa.Column('reopen_reason', sa.String(length=50), nullable=True))
    op.add_column('sighting', sa.Column('reopen_detail', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sighting', 'reopen_detail')
    op.drop_column('sighting', 'reopen_reason')
    op.drop_column('sighting', 'resolved_at')
    # ### end Alembic commands ###
