events {
    worker_connections 1024;
}

http {
    upstream backend_servers {
    server app-blue:8080;
}

    upstream frontend_server {
        server mengnyang-frontend:3000;
    }

    server {
        listen 80;

        # --- ???繹먭퍒?루춯? 嚥싳쉶瑗??꾧틡??????낇뀘????곗뒩泳??????딅젩 ---
        # /api/ ????嶺뚮??ｆ뤃???β뼯爰귨㎘??꿔꺂??袁ㅻ븶??????됰Ŋ?????꿔꺂??節뉖き???嶺뚮ㅎ????
        location /api/ {
            # proxy_pass ???녿뮝???????⑥쥓援??????/)?????거????レ탳?? ????⑤짅嫄х솾?
            # Nginx??醫딆쓧? ???嶺????Β??/api/ ???낇뀘????곗뒩泳?????곌퇈?뗦틦???野껊뿈???熬곣뫖利?????嶺뚮Ĳ?됲걫 ????썹땟????嶺뚮ㅎ????
            proxy_pass http://backend_servers;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # ?????룔꺈????? ?꿔꺂??袁ㅻ븶??????됰Ŋ???? ????썹땟怨⒲뀋?癲ル슢?????嶺뚮Ĳ?됲걫 ????썹땟????嶺뚮ㅎ????
        location / {
            proxy_pass http://frontend_server;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            # WebSocket ?꿔꺂?????
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }
}
