events {
    worker_connections 1024;
}

http {
    upstream backend_servers {
        server app-blue:8080;
    }

    upstream frontend_server {
        server mengnyang-frontend:3000;
    }

    server {
        listen 80;

        # --- ?�기가 ?�정??부분입?�다 ---
        # /api/ �??�작?�는 모든 ?�청??처리?�니??
        location /api/ {
            # proxy_pass 주소 ?�에 ?�래??/)�?추�??�면,
            # Nginx가 ?�동?�로 /api/ 부분을 ?�거?�고 백엔?�로 ?�달?�니??
            proxy_pass http://backend_servers;
            
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # ?�머지 모든 ?�청?� ?�론?�엔?�로 ?�달?�니??
        location / {
            proxy_pass http://frontend_server;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }
}
